### ISSUE TITLE
[BUG] Not saving world

### ISSUE THREAD

**Issue by orangemn6** [thecoder-001/MineColab#10]
**Describe the bug**
whenever I play on it it deletes the world

**To Reproduce**
Start server
join
restart
world gone
**Expected behavior**
For the world to save
**Screenshots**

**Minecraft server Version**
1.16.3 paper

**Mod/Datapack list**
worldedit
all the multiverse mods
nolagg

**Comment by kansielvin** [comment]
to save the world you need to type "stop" on the running server section before shutting down.
cmiiw

**Comment by thecoder-001** [comment]
Hello.
Yes it seems to be an issue of force closing the server (without using `stop` command) as @kansielvin suggested. The server has a a `auto-save-interval` which determines the time after which the server saves the world changes (default is 5 minutes). So, either you can manually stop the server or change the values of  `auto-save-interval` and `max-auto-save-chunks-per-tick` in your server's `paper.yml`.

**Comment by orangemn6** [comment]
I have been using stop to shut it down, but it still is not working

**Comment by thecoder-001** [comment]
The behavior was being caused by an anti-lag plugin. Closing the issue now.
