### ISSUE TITLE
[Feature Request]Region change on ngrok

### ISSUE THREAD

**Issue by kansielvin** [thecoder-001/MineColab#11]
Default Region on ngrok is US, and it's very lagging since we are playing minecraft are not from US

it will be so greatful if there is a new code for region change on ngrok.

**Comment by thecoder-001** [comment]
Hello!
That's a nice suggestion. I would try to add it as soon as I get some spare time.
Thanks.

**Comment by thecoder-001** [comment]
Implemented in #12

**Comment by kansielvin** [comment]
thank you very much! this really help a lot
