### ISSUE TITLE
[BUG] Cant connect to SSH acess to host OS

### ISSUE THREAD

**Issue by yougeshlama** [thecoder-001/MineColab#18]
**Describe the bug**
 i cant connect to the ssh 

**To Reproduce**
1. Run the minecraft server cell.
2. After the server started i turned off.
3. Scroll down to 'SSH access to host OS'
4. Run the cell off SSH access to host OS
5. Then putted the ngrok authtoken
6. Then run the second cell which contains the ip for the ssh it like tcp://0.tcp.ngrok.io:16826
7. Opened the putty on computer
8. typed the ip:root@0.tcp.ngrok.io port:16826
9. refused to connect the connection error + even if i connect there willl be no any minecraft server running on it or any files or directories are there on the ssh

**Expected behavior**
I thought i could control the server by this and access the files on it (ssh).

**Minecraft server Version**
1.16.3 paper

**Mod/Datapack list**
N/A 

**Additional context**
Please Help me if my procedure is wrong and merge a help guide. So it will be easy for like me

**Comment by thecoder-001** [comment]
Hello!
Unfortunately ssh access to the server has been broken for some time after google's change in the vm's security policies. A fix has been found currently, but it's a hassle to use & hence hasn't been implemented. Would try to fix it as soon as possible and if anyone else stumbles across a solution, feel free to submit a pr.
Cheers!

**Comment by yougeshlama** [comment]
ok thanks for replying :) I wish you will implement it soon as possible :)
