### ISSUE TITLE
[BUG] Can't connect to server

### ISSUE THREAD

**Issue by JarnoXCZ** [thecoder-001/MineColab#21]
Everything works and starts, but when i try to connect via the IP it won't connect. Im getting the IP from the ngrok connections.

**Comment by infinitygamer404** [comment]
@JarnoXCZ Can you send a screenshot of your problem? Which ngrok IP did you try to connect and what error did Minecraft give?
Did it ever work for you before?

**Comment by JarnoXCZ** [comment]
t=2021-01-07T11:15:23+0000 lvl=warn msg="failed to open private leg" id=6ab58daefa0e typ=proxy privaddr=localhost:25565 err="dial tcp 127.0.0.1:25565: connect: connection refused"

**Comment by JarnoXCZ** [comment]
And it never worked before. 
![image](https://user-images.githubusercontent.com/48828566/103886788-4ecfbc00-50e2-11eb-92c8-8f5d065e8610.png)

**Comment by infinitygamer404** [comment]
> t=2021-01-07T11:15:23+0000 lvl=warn msg="failed to open private leg" id=6ab58daefa0e typ=proxy privaddr=localhost:25565 err="dial tcp 127.0.0.1:25565: connect: connection refused"

That seems to be a small server side issue? Its only in the console, have you tried *actually* connecting to the ip (0.tcp.ngrok.io:16649 in this specific case) inside Minecraft? If so, then what does Minecraft say?

**Comment by infinitygamer404** [comment]
I've also found this by googling your error: https://github.com/inconshreveable/ngrok/issues/244

**Comment by DivyamChandalia** [comment]
> > t=2021-01-07T11:15:23+0000 lvl=warn msg="failed to open private leg" id=6ab58daefa0e typ=proxy privaddr=localhost:25565 err="dial tcp 127.0.0.1:25565: connect: connection refused"
> 
> That seems to be a small server side issue? Its only in the console, have you tried _actually_ connecting to the ip (0.tcp.ngrok.io:16649 in this specific case) inside Minecraft? If so, then what does Minecraft say?

I got the same error and when I tried to connect through Minecraft I got "could not connect to server" error

**Comment by infinitygamer404** [comment]
> > > t=2021-01-07T11:15:23+0000 lvl=warn msg="failed to open private leg" id=6ab58daefa0e typ=proxy privaddr=localhost:25565 err="dial tcp 127.0.0.1:25565: connect: connection refused"
> > 
> > 
> > That seems to be a small server side issue? Its only in the console, have you tried _actually_ connecting to the ip (0.tcp.ngrok.io:16649 in this specific case) inside Minecraft? If so, then what does Minecraft say?
> 
> I got the same error and when I tried to connect through Minecraft I got "could not connect to server" error

even after restarting the server? the issue must be an ngrok issue probably. We should try to use something other than ngrok in the near future because ngrok seems to have all kinds of these problems.

**Comment by orangemn6** [comment]
When I get ngrok issues like this, I use a VPN and it solves everything

**Comment by JarnoXCZ** [comment]
I'd like to thank infinitygamer404, I was putting in the IP Adress instead of the ngrok tcp IP.
When i did that it worked! Thanks.

**Comment by infinitygamer404** [comment]
Closing...

**Comment by DivyamChandalia** [comment]
![image](https://user-images.githubusercontent.com/77056490/104010807-19ef6200-51d3-11eb-8d66-4a91643e7f0b.png)
everytime i try to connect to the server i get this error and on minecraft i get"Disconnected". i am using the tcp address which was 0.tcp.ngrok.io:16649 something like this

**Comment by infinitygamer404** [comment]
@DivyamChandalia have you tried using a VPN? or changing the ngrok region?

**Comment by DivyamChandalia** [comment]
> @DivyamChandalia have you tried using a VPN? or changing the ngrok region?
> And are you 100% sure you are using the correct ngrok tcp link every time? (it changes every time)

Yep I am using the TCP link I will try changing the region and using a VPN and get back to you.
Thank you.

**Comment by DivyamChandalia** [comment]
Ok I got it to work, I don't know exactly what was wrong but I just reinstalled the server and it just started working.
Well thanks anyways :)

**Comment by spiderlord202** [comment]
> Ok I got it to work, I don't know exactly what was wrong but I just reinstalled the server and it just started working.
> 
> Well thanks anyways :) 
What was your configuration for ngrok? I am asking because I am having the same issue

**Comment by spiderlord202** [comment]
> > Ok I got it to work, I don't know exactly what was wrong but I just reinstalled the server and it just started working.
> > 
> Well thanks anyways :) 

What was your configuration for ngrok? I am asking because I am having the same issue

**Comment by MeteoritoAlpha** [comment]
I had the same problem as you guys, but i got it to work again. My issue was that i made a tunnel to 25545 instead of 25565. Maybe thats also your problem, spiderlord202. Cheers!

Sorry for the bad english.

**Comment by yudl** [comment]
same problem tried everything nothing worked...

**Comment by thjaed** [comment]
in your server.properties file make sure that server_ip is set to localhost, or try 127.0.0.1. This fixed it for me.
