### ISSUE TITLE
[BUG]Server Stops.

### ISSUE THREAD

**Issue by yougeshlama** [thecoder-001/MineColab#22]
**Describe the bug**
Server Stops Automatically after 90 minutes
**To Reproduce**
Started the server
closed the chrome
and open mc connect to 
the server

**Expected behavior**
i thought it will last long to the 12 hours as it is the time limit

**Screenshots**

**Minecraft server Version**
paper/spigot 1.16.3

**Mod/Datapack list**
N/A

**Additional context**
Is there any way to make server last long till 12 hour or may be until while i play.
I cant open both chrome and mc cause i have Potato laptop

**Comment by DivyamChandalia** [comment]
> **Describe the bug**
> Server Stops Automatically after 90 minutes
> **To Reproduce**
> Steps to reproduce the behavior:
> Started the server
> closed the chrome
> and open mc connect to
> the server
> 
> **Expected behavior**
> i thought it will last long to the 12 hours as it is the time limit
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Minecraft server Version**
> paper/spigot 1.16.3
> 
> **Mod/Datapack list**
> N/A
> 
> **Additional context**
> Is there any way to make server last long till 12 hour or may be until while i play.
> I cant open both chrome and mc cause i have Potato laptop

There is a 90 min time limit if you aren't active on the page
You could open chrome on your phone or just open the page again every like hour to renew the time limit

**Comment by infinitygamer404** [comment]
Issue/misunderstanding resolved, closing
