### ISSUE TITLE
[BUG]To make the IP constant 

### ISSUE THREAD

**Issue by yougeshlama** [thecoder-001/MineColab#23]
**Describe the bug**
The ip doesn't be always constant.
**Expected behavior**
I thought the ip would be always the same 

**Screenshots**

**Minecraft server Version**
1.16.3

**Mod/Datapack list**
N/A

**Additional context**
we are having problem because the ip doesn't remain always the constant we always need to add new ip to join the server.
if there is any way to make the ip constant then please fix this issue 

-Hoping For Postitive Response. :)

**Comment by YOYITsM3M8** [comment]
This is a thing with ngrok/google colab

**Comment by thecoder-001** [comment]
Yea, as YOYITsM3M8 said Ngrok only gives out static its for paid customers. A different service is being currently looked into but since its setup is a little bit too hacky, we are looking for a good way to integrate it well.

Cheers
