### ISSUE TITLE
[BUG] World save problem

### ISSUE THREAD

**Issue by sudo216** [thecoder-001/MineColab#27]
**Describe the bug**
whenever the run time disconnect's (automatically it shut downs ). Then my world just revert back at its state when i first started the server.

**To Reproduce**
Turned on the server.
joined in.
played and 
automattically disconnect's even the browser is on and then whenever i start the server again it reverts back it doesnot save the things which was before that i made but the inventry remains same.

**Expected behavior**
It shuld start from the same place and the all the things should have been saved properly.

**Screenshots**
N/A

**Minecraft server Version**
1.16.3
**Mod/Datapack list**
sleep-most, co-ordinate hud

**Additional context**
If there is any fix for this please help. I have resetted the server more than 5 times due to this problem now iam reporting it. :)

Hoping For Positive respsone

**Comment by Merendino1234** [comment]
idk before the 12 hours i stop and save the server...

another topic:
Do you have any idea to reduce lag in modded minecraft?
(c.a 180mods)

**Comment by yougeshlama** [comment]
now the server is starting slower i guess due to the intensive use of people but in night it open fastly :(

**Comment by infinitygamer404** [comment]
> another topic:
> Do you have any idea to reduce lag in modded minecraft?
> (c.a 180mods)
@Merendino1234 you can talk about stuff like that in the discussion section (https://github.com/thecoder-001/MineColab/discussions/13)

**Comment by thecoder-001** [comment]
> automattically disconnect's even the browser is on and then whenever i start the server again it reverts back it doesnot save > the things which was before that i made but the inventry remains same.
That's weird...maybe something to do with autosave timings? There's not much that can be done here on our side, it looks like either your save time in your server config is very long or some mod is acting up. Or it can be a faulty server jar.

**Comment by yougeshlama** [comment]
@thecoder-001 its set to 1 min atlthough and there is no mod installed its just a paper /spigot

**Comment by thecoder-001** [comment]
Unfortunately, I wasn't able to pinpoint what exactly was going wrong and others seem to have no problems with it.
Currently closing as stale. Feel free to reopen if the problem reoccurs or you are able to collect more info on the issue.
