### ISSUE TITLE
[Feature Request] update to 1.18

### ISSUE THREAD

**Issue by Zedroid1** [thecoder-001/MineColab#59]
yeah Im just gonna wait till update to 1.18

btw thank you guys

**Comment by MrJacksonCJ** [comment]
!!SORRY FOR MY ENGLISH!!
I try this 

!apt-get install openjdk-17-jdk-headless -qq > /dev/null
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-17-openjdk-amd64"
!update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/jre/bin/java
!java -version

after 
import os
import re

and IT'S WORKING

I HOPE HELP YOU

**Comment by MrJacksonCJ** [comment]
![IMG_20211207_100008.jpg](https://user-images.githubusercontent.com/90112124/145053152-b25649b1-7e18-427c-886a-d4f1c8c5dc8c.jpg)

**Comment by Zedroid1** [comment]
nope still cant run
Error: Unable to access jarfile server.jar

**Comment by MrJacksonCJ** [comment]
Sorry,  you must download mc sever paper server .jar lasted versión and rename server.jar and upload to folder Minecraft server and run again

**Comment by Zedroid1** [comment]
yep its running, thanks you .
but after 1hr running in google colab wont connect anymore, its say no backend lol

**Comment by thecoder-001** [comment]
Support added in #60.
