### ISSUE TITLE
[Feature Request] How to run forge 1.18.1

### ISSUE THREAD

**Issue by Sgambe33** [thecoder-001/MineColab#65]
Hi, I tried installing forge but since java 17 they changed the way to start the server. You now have to start a bash file instead of a jar. I was wondering if forge support could be added considering that when I try to run the bash it gives me serveral errors.

**Comment by thecoder-001** [comment]
Hello!
Unfortunately, I'm not able to get a lot of spare time these days to work on my projects (uni exams) and development of the project has slowed down. While it would be nice to have forge support out of the box, for now you can try to change:
```bash
java $memory_allocation $server_flags -jar $jar_name nogui
```
to
```bash
bash run.sh
```
and edit the file `user_jvm_args.txt` to add `-Xmx6144M -Xms6144M` in the end and you should be good to go.
Report back if it doesn't works.
Cheers!
