### ISSUE TITLE
Console Commands?

### ISSUE THREAD

**Issue by Software-Wolf** [thecoder-001/MineColab#66]
**Describe the bug**
Can't send console commands.

**To Reproduce**
1. Go to server on colab
2. Try to send a command (like OP yourself)

**Expected behavior**
You would expect the command to go through, but it does not.

**Screenshots**
![image](https://user-images.githubusercontent.com/72639865/151736801-c5810834-2267-4f6d-b708-52946319f385.png)

**Minecraft server Version**
1.17.1 (not sure if its running paper or vanilla)

**Mod/Datapack list**
None

**Additional context**
n/a

**Comment by thecoder-001** [comment]
Hello!
Oops...that was an unfortunate mistake.
Fixed in the commit bcda3d66619d0b1c53af15f6aae3823b6c0009fd.

![Screenshot 2022-05-30 at 2 38 55 AM](https://user-images.githubusercontent.com/25097841/170891693-58b9bace-4546-4275-9a40-a56de48ebdde.png)
