### ISSUE TITLE
[Feature Request] Adding playit.gg as a forwarding option

### ISSUE THREAD

**Issue by christianfirecup** [thecoder-001/MineColab#69]
**Is your feature request related to a problem? Please describe.**
This is a fantastic piece of software but it discourages players from playing when the IP changes every time playit.gg would fix that

**Describe the solution you'd like**
I would like you guys to add play it gg as an option for forwarding if it isn't too much trouble I've seen people do it before

**Describe alternatives you've considered**
Argo needs third party software so that wouldn't work for me 

**Additional context**
If this isn't possible that is completely fine

**Comment by thecoder-001** [comment]
Hello there!
Sorry for the late response (was busy with life/uni) but if you're still interested, the latest pr adds intial support for playit.gg.
While its not the most polished thing in the world right now(alot of debug log spam that needs to be filtered out), it seems to be working pretty ok.

Cheers!
